name: "Release package"
on: 
  push:
    branches:
      - master

jobs:
  release_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "yarn install"
        run: yarn install --frozen-lockfile

      - name: "npm run semantic-release"
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}